# Generated by Django 3.0.6 on 2020-05-12 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_resized.forms
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 5, 12, 5, 22, 13, 917054, tzinfo=utc))),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('fullshot', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=report.models.user_path)),
                ('detailshot', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=report.models.user_path)),
                ('menushot', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=report.models.user_path)),
                ('youtubelink', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('gukmool', models.IntegerField()),
                ('gogi', models.IntegerField()),
                ('kimchi', models.IntegerField()),
                ('service', models.IntegerField()),
                ('weesaeng', models.IntegerField()),
            ],
        ),
    ]
