# Generated by Django 3.0.6 on 2020-05-20 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_resized.forms
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detailshot',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[960, 540], upload_to=report.models.user_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='fullshot',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[960, 540], upload_to=report.models.user_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='menushot',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[960, 540], upload_to=report.models.user_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 5, 20, 12, 10, 59, 295123, tzinfo=utc)),
        ),
    ]
