# Generated by Django 3.0.6 on 2020-06-02 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_resized.forms
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200520_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 2, 15, 49, 49, 443620, tzinfo=utc))),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('open_close', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('youtubelink', models.TextField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 2, 15, 49, 49, 441621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report2',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 2, 15, 49, 49, 442621, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Weesaeng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('table', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('spoons', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('cups', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('kitchen', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('tissue', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('toilets', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weesaeng', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banchanTime', models.CharField(max_length=10)),
                ('gukbaptime', models.CharField(max_length=10)),
                ('kindness', models.CharField(choices=[('3', '상'), ('2', '중'), ('1', '하')], max_length=10)),
                ('banchanRefill', models.CharField(choices=[('yes', 'O'), ('no', 'X')], max_length=10)),
                ('selfServing', models.CharField(choices=[('yes', 'O'), ('no', 'X')], max_length=10)),
                ('gukmulRefill', models.CharField(choices=[('yes', 'O'), ('no', 'X')], max_length=10)),
                ('dessert', models.CharField(choices=[('yes', 'O'), ('no', 'X')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[960, 540], upload_to=report.models.report_dir_path)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='Kimchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spicy', models.CharField(choices=[('5', '상'), ('4', '상중'), ('3', '중'), ('2', '중하'), ('1', '하')], max_length=10)),
                ('banchan', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kimchis', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='Gukmool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuksu', models.CharField(choices=[('bone', '뼈'), ('meat', '살코기'), ('mix', '혼합')], default='bone', max_length=50)),
                ('yeomdo', models.CharField(max_length=50)),
                ('hexColor', models.CharField(max_length=50)),
                ('saewoo', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('salt', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('blackPepper', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('toRyeom', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('yangNyeomJang', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('ddaroGukbap', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('NETgukbap', models.CharField(choices=[('yes', 'O'), ('no', 'X')], default='O', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gukmools', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='Gogui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meatPart', models.CharField(max_length=50)),
                ('texture', models.CharField(choices=[('soft', '부드러움'), ('jol', '쫄깃함'), ('hard', '퍽퍽함')], max_length=30)),
                ('thickness', models.CharField(choices=[('thin', '얇음'), ('thick', '두꺼움')], max_length=30)),
                ('smell', models.CharField(choices=[('5', '상'), ('4', '상중'), ('3', '중'), ('2', '중하'), ('1', '하')], max_length=10)),
                ('dippingSource', models.CharField(choices=[('yes', 'O'), ('no', 'X')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goguis', to='report.Report3')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.Report3')),
            ],
        ),
    ]
