# Generated by Django 3.0.6 on 2020-06-06 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200603_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 6, 8, 35, 40, 892873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report2',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 6, 8, 35, 40, 893872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report3',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 6, 6, 8, 35, 40, 894872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report3',
            name='youtubelink',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weesaeng',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weesaengs', to='report.Report3'),
        ),
        migrations.CreateModel(
            name='Latlng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latlngs', to='report.Report3')),
            ],
        ),
    ]
